title: EvoBioSys — Evolving Living Systems
description: Cultivating evolutionary approaches & liberating systems. A holonic network of projects, collectives, and individuals.
url: "https://evobiosys.org"
baseurl: ""

markdown: kramdown
theme: null
plugins:
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - access-test.md
  - test-pr.txt
